aliyun.oss.file.endpoint=\u4F60\u7684endpoint\u5730\u5740
aliyun.oss.file.keyid=\u4F60\u7684access-key-id
aliyun.oss.file.keysecret=\u4F60\u7684access-key-secret
aliyun.oss.file.bucketname=\u4F60\u7684bucket\u540D\u79F0